### ISSUE TITLE
Link to the status dashboard from the SearchWorks 500 page

### ISSUE THREAD

**Issue by ahafele** [sul-dlss/searchworks-status#131]
https://searchworks.stanford.edu/500.html

**Comment by jvine** [comment]
<img width="552" alt="screen shot 2018-10-25 at 2 33 54 pm" src="https://user-images.githubusercontent.com/6945691/47531633-0ad6a080-d863-11e8-99bf-782fc47fefa3.png">

```
<h1>We're sorry, this service is unavailable.</h1>
<p>The operations team is aware of the issue.</p>
<p>Check the <a href="">system status page</a> for updates.</p>
```

- [ ] Remove the `If you are the application owner` line - it sort of implies we aren't aware of the issue and isn't telling the app owner anything they don't know.

Otherwise intended to match wording on system page (about availability, ops team). Let me know if you think the text is inaccurate or insufficiently (or too) generic.
