### ISSUE TITLE
Use NewRelic API to determine when we're in a degraded service state e.g. "issue"

### ISSUE THREAD

**Issue by cmh2166** [sul-dlss/searchworks-status#5]
Question needing to be answered

**Comment by mejackreed** [comment]
My thought is sw app, apdex < 0.75. This is kind of arbitrary, but we can move this later on if we need to. Though I don't think we have a way to set this in any measurable way, do we?

cc @jkeck @aeschylus @camillevilla

**Comment by mejackreed** [comment]
I think @aeschylus looked into the API key at one point and may have some more information.

**Comment by aeschylus** [comment]
I'm not sure if this goes through their "insight" tool, but if so, you pay per API call. I also never got it to actually give me a response on the command line or in the browser terminal, but I'll give this a try.

**Comment by jkeck** [comment]
It looks like its not part of the insight tool as it appears to be part of their standard REST API.  Setting up Alerts is a paid feature, but one that is included in our subscription level. 

Their alert system appears to be geared towards pushing alerts out to (e.g. email, slack, etc) but we can also setup an alert with no communication channels and it will only be available through their REST API.

We can setup a critical or warning threshold, although we probably just want to consider a critical threshold since we're talking about programmatic access.  One thing to note, is that the minimum amount of time we need to be below our configured threshold is 5 minutes (there is no lower setting).  So our apdex will need to fall below our threshold (.75) for 5 minutes before an alert will be triggered.

We also have the ability to setup various other checks against our external services solr, etc, but we may want to decide if A) this is a good idea first, and if so, B) if that would be a check of solr itself or how SearchWorks reports solr is responding.

**Comment by mejackreed** [comment]
My 2 cents here:

> A) this is a good idea first

I'm not so sure. If a user is experiencing an issue they may go check the status page for immediate feedback. If we have a 5min delay (assuming it all works) then they are not going to see that status change and may experience further frustration. I guess this might be better than nothing, but may not provide the original intended value. So in the long run, is it worth adding this feature?
