### ISSUE TITLE
Figure out responsivness for header

### ISSUE THREAD

**Issue by mejackreed** [sul-dlss/searchworks-status#78]
Spun out of #58.

**Comment by jvine** [comment]
Some suggestions:

- Remove the special margins and padding from `.brand-logo` `.title` and `.nav-menu`, and instead apply `align-items: center;` to `.header`. 
- For `@media (max-width: 768px)` use the rosette alone instead of the full logo https://consul.stanford.edu/display/Logos/Home?preview=/138077104/156206495/Rosetteonly.jpg
- For `@media (max-width: 768px)` reduce the h1 font size to the h2 size `font-size: 1.953em;`
- Add `display:flex` to `.nav-menu` 

And for the remainder of the page:
- The `.status-legend` key in the Current service status section is problematic at several breakpoints. Since the icons are self-explanatory and always accompanied by the equivalent text, maybe we can just remove that section altogether and center the h2 like the others on the page. 
- For `@media (max-width: 768px)`, set the horizontal padding to 10px for `.section` and `.services`. Otherwise the main page content is reduced to a tiny column and the graphs aren't usable.

<img width="405" alt="screen shot 2018-09-27 at 2 14 21 pm" src="https://user-images.githubusercontent.com/6945691/46175092-ad4d3500-c25f-11e8-95df-373fc3576b44.png">
